# Generated by Django 2.2.3 on 2019-07-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190710_0705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_view_book', 'Can view book'), ('can_view_instance', 'Can view book instance'))},
        ),
    ]
